### ISSUE TITLE
生成作者 rss 错误

### ISSUE THREAD

**Issue by amwps290** [hutushen222/JianshuRSS#10]
想生成某个作者的 rss, 发现生成的是首页的rss

**Comment by ShimotsukiH** [comment]
同样遇到问题 在输入框中写入作者的首页地址 返回的连接在feeldy填入 显示的是首页的rss……求作者教教怎么用……

**Comment by hutushen222** [comment]
我这个周末看下

**Comment by hutushen222** [comment]
已修复，兼容了简书的 HTTPS 协议的链接

**Comment by ShimotsukiH** [comment]
谢谢~

Jack Hu <notifications@github.com>于2018年6月22日周五 上午12:17写道：
