### ISSUE TITLE
似乎已无法使用？

### ISSUE THREAD

**Issue by pangbobo** [hutushen222/JianshuRSS#3]
在生成新的RSS时有Error信息如下：
Error
A website error has occured. The website administrator has been notified of the issue. Sorry for the temporary inconvenience.

另，之前生成的RSS链接也已失效。

辛苦了，谢谢。

**Comment by zifeixu85** [comment]
对呀  貌似失效了，看RSS里的订阅好久没更新了，以为没发表。结果去网站一看错过好多了
