### ISSUE TITLE
部分url不支持

### ISSUE THREAD

**Issue by wizardforcel** [hutushen222/JianshuRSS#4]
1. 不支持`/trending/weekly`、`/trending/monthly`、和`/trending/new`。
2. 不支持`notes`下的`category_id`细分。

希望作者能修复。谢谢。

**Comment by hutushen222** [comment]
@wizardforcel 我周末抽时间看下，也许会处理。

如果你能够贡献代码话更好，那样我就能够更快的部署到线上。
