### ISSUE TITLE
无法使用RSS输出

### ISSUE THREAD

**Issue by AaronL-ee** [hutushen222/JianshuRSS#6]
可以打开网页，制作RSS输出，反馈5000

**Comment by hidezember** [comment]
无法制作RSS输出，希望作者有空能修复一下，感谢

Error

A website error has occurred. The website administrator has been notified of the issue. Sorry for the temporary inconvenience.

**Comment by hutushen222** [comment]
@AaronL-ee @hidezember 服务器出了点问题，已修复。
