### ISSUE TITLE
你好，请问你提供的转rss输出的链接会一直有效吗

### ISSUE THREAD

**Issue by dengyhgit** [hutushen222/JianshuRSS#7]
你好，http://jianshu.milkythinking.com/ 这个链接会一直有效么，我可以直接使用你的源码部署在我的服务器上吗？

**Comment by hutushen222** [comment]
这个项目从 13 年 08 月份跑到了现在，可预见的时间内应该还是会继续跑着，不保证一直有效。
***
你可以直接部署到的自己的服务器。

**Comment by dengyhgit** [comment]
@hutushen222  非常感谢
