### ISSUE TITLE
主站milkythinking.com访问不了了

### ISSUE THREAD

**Issue by BoWuGit** [hutushen222/JianshuRSS#8]
rss输出是ok的，但现在主站访问不了，能修一下吗，谢谢。

**Comment by hutushen222** [comment]
@BoWuGit IP 被禁，我这几天会更换主机，到时候就好了

**Comment by BoWuGit** [comment]
好的，谢谢

**Comment by HiChina01** [comment]
你好，请问出现如下问题应该如何解决？
Parse error: syntax error, unexpected ':', expecting '{' in D:\JianshuRSS\library\functions.php on line 54

**Comment by hutushen222** [comment]
目前站点是可以访问的了
