### ISSUE TITLE
你好请教一个使用问题。

### ISSUE THREAD

**Issue by HiChina01** [hutushen222/JianshuRSS#9]
你好，今天使用了您的程序发现运行时报错
Parse error: syntax error, unexpected ':', expecting '{' in D:\JianshuRSS\library\functions.php on line 54
我对php不熟悉实在不知道能怎么办，希望作者能指导一二谢谢

**Comment by hutushen222** [comment]
那里使用了 PHP 7 的特性，你可以升级一下环境。

**Comment by HiChina01** [comment]
好的谢谢一会儿我去试试嘿嘿

**Comment by HiChina01** [comment]
我的php版本现在是7.0.12又出现了这么个问题能否问一下是因为什么嘛？
Fatal error: Uncaught Error: Class 'Slim\Slim' not found in D:\JianshuRSS\public\index.php:7 Stack trace: #0 {main} thrown in D:\JianshuRSS\public\index.php on line 7
